version: '2'

volumes:
  data.postgres:
    driver: "local"
  data.opennms:
    driver: "local"
  data.graylog.es.01:
    driver: local

networks:
  net.dc:
      driver: bridge
      ipam:
        config:
          - subnet: 172.30.0.0/16
  net.branch:
      driver: bridge
      ipam:
        config:
          - subnet: 172.31.0.0/16
services:
  database:
    image: postgres:9.6.1
    container_name: database
    env_file:
      - .postgres.env
    environment:
      - TZ=Europe/Berlin
    ports:
      - "5432:5432"
    volumes:
      - data.postgres:/var/lib/postgresql/data
    networks:
      net.dc:
        ipv4_address: 172.30.0.10

  opennms:
    image: opennms/horizon-core-web:20.0.1-1
    container_name: horizon-core-web
    cap_add:
      - NET_ADMIN
    networks:
      net.dc:
        ipv4_address: 172.30.0.11
    env_file:
      - .opennms.env
      - .postgres.env
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - database
    volumes:
      - data.opennms:/opennms-data
      - ./etc:/opt/opennms/etc
    command: ["-s"]
    ports:
      - "8980:8980"
      - "18980:18980"
      - "1099:1099"
      - "8101:8101"
      - "61616:61616"
      - "5817:5817"
      - "162:162/udp"

  grafana:
    image: opennms/helm-app
    container_name: helm
    networks:
      net.dc:
        ipv4_address: 172.30.0.9
    environment:
      - TZ=Europe/Berlin
    env_file:
      - .grafana.env
    ports:
      - "3000:3000"

  minion:
    image: opennms/minion:20.0.1-1
    container_name: minion
    networks:
      net.dc:
        ipv4_address: 172.30.0.12
      net.branch:
        ipv4_address: 172.31.0.12
    env_file:
      - .minion.env
    command: ["-f"]
    ports:
      - "8201:8201"
      - "18980"
      - "162/udp"
      - "514/udp"

  dc.srv.01:
    image: indigo/docker-netsnmp
    container_name: dc.srv.01
    networks:
      net.dc:
        ipv4_address: 172.30.0.32
    environment:
      - TZ=Europe/Berlin
    ports:
      - "161/udp"

  dc.srv.02:
    image: indigo/docker-netsnmp
    container_name: dc.srv.02
    networks:
      net.dc:
        ipv4_address: 172.30.0.33
    environment:
      - TZ=Europe/Berlin
    ports:
      - "161/udp"

  dc.web.01:
    image: httpd
    container_name: dc.web.01
    networks:
      net.dc:
        ipv4_address: 172.30.0.34
    environment:
      - TZ=Europe/Berlin
    ports:
      - "80"

  branch.srv.01:
    image: indigo/docker-netsnmp
    container_name: branch.srv.01
    networks:
      net.branch:
        ipv4_address: 172.31.0.32
    environment:
      - TZ=Europe/Berlin
    ports:
      - "161/udp"

  branch.srv.02:
    image: indigo/docker-netsnmp
    container_name: branch.srv.02
    networks:
      net.branch:
        ipv4_address: 172.31.0.33
    environment:
      - TZ=Europe/Berlin
    ports:
      - "161/udp"

  branch.web.01:
    image: httpd
    container_name: branch.srv.01
    networks:
      net.branch:
        ipv4_address: 172.31.0.34
    environment:
      - TZ=Europe/Berlin
    ports:
      - "80"

  graylog_mongodb:
    image: mongo:3
    container_name: graylog-mongodb
    hostname: mongo
    environment:
      - TZ=Europe/Berlin
    networks:
      net.dc:
        ipv4_address: 172.30.0.13

  graylog_es:
    image: elasticsearch:2
    container_name: graylog-es-01
    hostname: elasticsearch
    command: elasticsearch -Des.cluster.name='graylog'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      mem_limit: 1g
    volumes:
      - data.graylog.es.01:/usr/share/elasticsearch/data
    environment:
      - TZ=Europe/Berlin
    networks:
      net.dc:
        ipv4_address: 172.30.0.14

  graylog:
    image: graylog2/server:2.2.3-1
    hostname: graylog
    environment:
      - TZ=Europe/Berlin
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    links:
      - graylog_mongodb:mongo
      - graylog_es:elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "514:514/udp"
    networks:
      net.dc:
        ipv4_address: 172.30.0.15
